### ISSUE TITLE
Fix corner cases that crash the tool

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#11]
The following situations currently crash the app:
- a new point is added to the points layer (we should just deactivate this)
- a new label is added to the segmentation or a label is removed from the segmentation (we need to adjust the update function to handle these cases)

**Comment by constantinpape** [comment]
@sofroniewn
What would be the best way to deactivate the option of adding new points in the points layer?
The points are added automatically from the centroids and we don't want them to be modified by nosy users ;).

**Comment by kevinyamauchi** [comment]
Unfortunately, as far as I know, we do not have a nice way to disable the adding points button in the public API (it's on the roadmap, see https://github.com/napari/napari/issues/1273).

Here is a hacky way that I know of. Perhaps @sofroniewn or @tlambert03 know of a better way...

```python

# get the dictionary containing the layer control widgets
control_widgets = viewer.window.qt_viewer.controls.widgets

# get the controls for the points layer of interest (the key is the layer itself
points_controls = control_widgets[viewer.layers[<name of points layer>]]

# disable the point adding button 
points_controls.addition_button.setEnabled(False)
```

While you're at it, you might want to disable the select button as well. You could then include your own "mode" button in your custom dock widget that selects the points layer, sets the mouse click callbacks in the right order for your point label iterating to work property (as discussed in https://github.com/hci-unihd/covid-if-annotations/issues/10#issuecomment-633870697).

```python
# you can also disable the select button
points_controls.select_button.setEnabled(False)
```

**Comment by constantinpape** [comment]
> While you're at it, you might want to disable the select button as well. You could then include your own "mode" button in your custom dock widget that selects the points layer, sets the mouse click callbacks in the right order for your point label iterating to work property

Ok, that sounds like the right way to fix that bug!
I will try to implement it later.

**Comment by constantinpape** [comment]
Ok, I have disabled adding points like you suggested.
For fixing #10 I went with a different solution and kept the selection layer, see https://github.com/hci-unihd/covid-if-annotations/issues/10#issuecomment-634052909

**Comment by constantinpape** [comment]
Fixed the corner cases now.
