### ISSUE TITLE
Need to call function on viewer after the read hook

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#18]
I have a slight issue with the reader IO hook:

I have a function [modify_layers](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L33-L38), that needs to be called AFTER the layers have been added to the viewer.
This is fine if [the viewer is initialized with data](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/launcher/covid_if_annotations.py#L39-L40), but if I add data via the IO hook, I can't do this in the launch function.

Right now, I have a dirty fix by calling this in the keybindings, e.g. [here](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L62-L63), but this means when adding data through drag'n'drop the viewer is only fully initialized after the first keybinding is used.

This came up in https://github.com/hci-unihd/covid-if-annotations/issues/3#issuecomment-633146178 already, but I don't really see how the solution @tlambert03 suggests would help here, because while I am in the `napari_reader`, the layers have not been added to the viewer yet.

The only clean solution I can see here is to add a callback on the viewer that is called after the layers returned by the reader have been added.
But I am very happy to hear other suggestions, @sofroniewn, @tlambert03 :).

**Comment by tlambert03** [comment]
yeah, that's a tricky one... we had a _lot_ of discussions back when we were determining the initial API for reader plugins (https://github.com/napari/napari/pull/908 and https://github.com/napari/napari/pull/937) and it was decided at the time that we didn't want reader plugins to have access to the full viewer object (can't find the exact comments with rationale anymore).  So yeah, in this case there's nothing you can do within the plugin framework to access the viewer in a reader hook.  So I think a callback on the viewer is a good idea.  Maybe add a listener to the `viewer.layers.changed` or `viewer.layers.added` events?

**Comment by constantinpape** [comment]
>  Maybe add a listener to the `viewer.layers.changed` or `viewer.layers.added` events?

Thanks for the hints.
Is there some example code for adding a listener to these?

**Comment by tlambert03** [comment]
something like this:
```python
import napari

def on_layer_change(event):
    # the event object will have the following useful things:
    # event.source -> the full viewer.layers object itself
    # event.item -> the specific layer that cause the change
    # event.type -> a string like 'added', 'removed'
    ...

viewer = napari.Viewer()
viewer.layers.events.changed.connect(on_layer_change)
```

**Comment by constantinpape** [comment]
@tlambert03 ok, I implemented it now and it works partially for my use case:
adding the [mouse binding works fine](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L15-L17).

However, I also [need to get access to the viewer for disabling a button](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/_key_bindings.py#L42-L46).
And I don't know how to get access to the viewer through the event.

(For practical purposes the current solution is fine, disabling the button is not so important and it still happens after the first keybinding is used. But it would still be nice to know how to solve this.)

**Comment by kevinyamauchi** [comment]
I haven't tested this, but it looks like there is a [`layers_changed` event](https://github.com/napari/napari/blob/356da76f6306db0ac61565e5a2f63af0b385e5b0/napari/components/viewer_model.py#L384-L393) on the viewer that is [called when the layers changed event is called](https://github.com/napari/napari/blob/356da76f6306db0ac61565e5a2f63af0b385e5b0/napari/components/viewer_model.py#L87).

I think 

```python
viewer.events.layers_change.connect(on_layer_change)
```
will pass your callback the viewer. You might need to check that the callback isn't raised by anything else though and if so, add some logic to handle it.

**Comment by constantinpape** [comment]
@kevinyamauchi
Unfortunately I can't find a simple way to do this via 
`viewer.events.layers_change.connect(on_layer_change)`:
At the time when this is called, the layers have not been added yet.
So while I get the viewer, I can't change the properties that need to be changed yet.

Hope that makes sense.

In any case, this part is not so important, I will leave it as it is for now.

**Comment by sofroniewn** [comment]
> Hope that makes sense.
>
> In any case, this part is not so important, I will leave it as it is for now.

Makes sense, once this is all done, thinking about how to address this need through a plugin interface would be good. Glad you can still make progress

**Comment by constantinpape** [comment]
Ok, it turns out the issue comes up in some cases and is a bit annoying, because the user always has to press a shortcut before seeing the full changes take place.

From my point, the most elegant solutions would be to either include the viewer also in the event that is triggered here: `viewer.layers.events.changed.connect(on_layer_change)`
Or to have a pointer from each layer to the viewer.

But of course I don't know if this is compatible with the underlying napari design.

**Comment by tlambert03** [comment]
actually... a general point I'd make about the patterns in this repo is that it passes around the viewer as a variable to various functions in a way that might be making everything more complicated... especially since you really only have a single viewer instance for most cases.
(If you intended to support a lot of different viewer instances, I can see how that might be useful)

here though, because you are adding `on_layer_change` as a callback to your `viewer.layers.events.changed` signal... you _already have_ the viewer instance.  So you can enclose the viewer inside your callback:

```python
viewer = napari.Viewer()
def callback(event):
    print(viewer)  # it's in the local scope!

viewer.layers.events.changed.connect(callback)
```

Generally, that means you need to define your callback functions in the same scope as the viewer instance, but if you'd like to have a seperate function in your library somewhere that takes a viewer _and other things_, you can make a higher order function that encloses the viewer elegantly with [`functools.partial`](https://docs.python.org/3.8/library/functools.html#functools.partial):

```python
# file.py
def some_function(viewer, event):
    print(viewer, event)

# another_file.py
from .file import some_function
from functools import partial

viewer = napari.Viewer()
wrapped_func = partial(some_function, viewer)
viewer.layers.events.changed.connect(wrapped_func)
```

edit: ... all this to say, it would be reasonable, and fairly common, for your `launch_covid_if_annotation_tool` function (or perhaps the `connect_to_viewer` function) to be fatter, with much more logic to connect stuff to the viewer

**Comment by constantinpape** [comment]
@tlambert03 
yes, that's a good point.
I adapted the current design from `segmentify` and haven't changed it much;
just keeping some things in the viewer scope would make life easier for now.
I will see if it makes sense to update it later.

**Comment by constantinpape** [comment]
Ok, I moved `on_layer_change` into the viewer scope in 1b27180.
This makes everything much easier!
Thanks for the suggestion @tlambert03.
