### ISSUE TITLE
Install from source fails

### ISSUE THREAD

**Issue by jkh1** [hci-unihd/covid-if-annotations#32]
Everything runs fine until 
```
 > pip install -e .
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode
```

**Comment by constantinpape** [comment]
For this to work you need to be in the top-level `covid-if-annotations` directory.

**Comment by jkh1** [comment]
OK, somehow I wasn't in the right dir anymore. Sorry for the noise.

**Comment by constantinpape** [comment]
No worries ;). Thanks for trying it out.
