### ISSUE TITLE
Speed up segmentation to edge mask

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#7]
The function `get_edge_segmentation` is fairly slow, because it erodes all segments individually: 
https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/image_utils.py#L20-L30

Initially, I thought this would only be called once, so I didn't think about performance.
But now it is called every time the layers are updated and makes this step a bit unresponsive.
(I checked and it's much smoother if this is not activated).

Some options to speed this up:
- Vectorize / go to numba
- Use grayscale diation (would this work in this case?)

@jni any suggestiosn on this from the skimage side?

**Comment by jni** [comment]
@constantinpape I think what you're doing is equivalent to `segmentation.find_boundaries(..., mode='inner')`?

https://github.com/scikit-image/scikit-image/blob/eed7c719d5828f1f4b3312a642de95528d2eb3e6/skimage/segmentation/boundaries.py#L48-L180

It does indeed use grayscale dilation. =)

**Comment by constantinpape** [comment]
Thanks for sharing this, @jni.
I realized that what I did was really inefficient, I can just use `find_boundaries` to get the edge pixels,
dilate those, invert the results and then use this mask to zero out the segmentation.
