### ISSUE TITLE
Add shortcut and gui button for add new label

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#8]
Feedback from @akreshuk:
add a shortcut and button that selects the next available label and goes to the paint mode.

Can be added as a shortcut to the `cell-segmentation` layer.

**Comment by constantinpape** [comment]
I have implemented this in https://github.com/hci-unihd/covid-if-annotations/commit/9b996daf2209f9b3f4214ee0f9a824dc93d8c07c now.

@sofroniewn @tlambert03 first of all it's great how easy it is with keybindings + `magicgui` to do this :).

However, one thing does not work as I would expect it right now:
I tried to also change the active layer to the labels [in the gui function](https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/gui.py#L30-L32).
However, when I do this the layer does get changed, but the previously active layer is still "partially active". After pressing `get_next_label`, the `infected-vs-control` points layer is still marked as active, although I can paint in the labels layer already. See the second screenshot.

![Screenshot from 2020-05-25 15-38-05](https://user-images.githubusercontent.com/4263537/82818130-8add4600-9e9e-11ea-903e-f2ffe671fe93.png)
![Screenshot from 2020-05-25 15-38-53](https://user-images.githubusercontent.com/4263537/82818136-8d3fa000-9e9e-11ea-9479-e740e2401403.png)

Is this a napari bug or am I doing something wrong?

**Comment by tlambert03** [comment]
how about this?
```python
@magicgui(call_button='get next label [n]', viewer={"visible": False})
def paint_new_label_gui(labels: Labels, viewer: Viewer):
    viewer.layers.unselect_all()
    labels.selected = True
    paint_new_label(labels)
```

**Comment by constantinpape** [comment]
Yes, that works!
Thanks!

**Comment by tlambert03** [comment]
Also, if you want to make the behavior consistent between pressing the button and the `n` key, you might want to bind the `n` key to the viewer instead and put that logic in `paint_new_label` ...  you would need to "find" the labels layer though, which entails making some assumptions about the naming, or number of labels layers?

```python
@Viewer.bind_key('n')
def paint_new_label(viewer):
    viewer.layers.unselect_all()
    # if you know the name
    layer = viewer.layers['cell-segmentation']
    # if you want the first labels layer
    # (this syntax will error if there are no Labels)
    layer = next(l for l in viewer.layers if isinstance(l, Labels))
    layer.selected = True
    seg = layer.data
    next_label = seg.max() + 1
    layer.mode = 'paint'
    layer.selected_label = next_label
```

**Comment by constantinpape** [comment]
Yes, I thought about this too.
In this case, I know that it's caled `cell-segmentation`, so binding it to the viewer and hard-coding the name would work.

**Comment by sofroniewn** [comment]
Just want to note a couple points that i may then make issues out of on napari

We should reconsider how `active_layer` is exposed on the `viewer`. As you noticed changing that directly does all sorts of funny things, and it probably shouldn't be exposed there in this way at all. I'll make a note.

We should make sure if is easy to disable the editable nature of layer names so that users can't accidentally rename names that your functions have hardcoded to use

**Comment by constantinpape** [comment]
> We should reconsider how `active_layer` is exposed on the `viewer`. As you noticed changing that directly does all sorts of funny things, and it probably shouldn't be exposed there in this way at all. I'll make a note.

Yes, I agree. It should probably not be exposed as it is right now because it behaves in an unexpected manner.

> We should make sure if is easy to disable the editable nature of layer names so that users can't accidentally rename names that your functions have hardcoded to use

Yes, that would actually be really good to have for this project already!
I will also add an issue in this repository to keep track of that point.
