### ISSUE TITLE
Add a tooltip for the semantic label colors

### ISSUE THREAD

**Issue by constantinpape** [hci-unihd/covid-if-annotations#9]
Feedback from @akreshuk

Add a tooltip or similar that explains the semantic label colors:
white = unlabeled, red = infected, cyan = control, yellow = uncertain.

**Comment by constantinpape** [comment]
@sofroniewn
From your experience, what would be the easiest to add a tooltip or small GUI element with this information?

**Comment by sofroniewn** [comment]
We havn't provided too much ourselves to make this easy yet - my recomendation would be to follow the approach in https://github.com/napari/napari/issues/531#issuecomment-544766877 where the person hooks up a custom mouse function to their own mini Qt widget, which you could add as a viewer dock widget. Note that if you have a couple of these small widgets (either from magic gui or from here for example) you could add multiple dock widgets or combine them into one. You can also position the dock widgets on the four sides of the viewer too.

Let me know if you run into trouble here

**Comment by constantinpape** [comment]
Ok, I have added a first tooltip using a `QTWidgets.QLabel`:
https://github.com/hci-unihd/covid-if-annotations/blob/master/napari_covid_if_annotations/gui.py#L74-L76

I will still make this a bit more concise by just printing the label names in their respective color.
But I need to figure out how this works with QLabel first.

**Comment by constantinpape** [comment]
I cleaned this up a bit and put it in the same box as the other gui elements.
It looks much better already.
Eventually, I think we want to put a small image with examples in that box, but I am not sure if I have time for this before tomorrow.

**Comment by constantinpape** [comment]
Done.
